// RSI indicator
//
// Input configuration
// - sourceInput: close; the OHLC input for the RSI
// - lengthInput: 14; number of periods for the RSI
// - offsetInput: 0; 
//
// Output:
// - RSI solid line
// - Overbought dotted line
// - Oversold dotted line


//@version=5
indicator(title="Relarive Strength Index", shorttitle="RSI with timeframe", overlay=true, timeframe="D", timeframe_gaps=true)

// Configurable input fields
float   sourceInput = input.source(close, title="Source")
int     lengthInput = input.int(14, minval=1, title="Length")
int     offsetInput = input.int(title="Offset", defval=0, minval=-500, maxval=500)

// RSI is between 0 and 100
float rsi = ta.rsi(sourceInput, lengthInput)

// Plot RSI line
plot(rsi, color=color.blue, title="RSI", offset=offsetInput)

// Plot horizontal lines
hline(80, "Overbought", color=color.gray, linestyle=hline.style_dotted)
hline(20, "Oversold", color=color.gray, linestyle=hline.style_dotted)
